name: Viral_meta_ML
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.8
  - pandas=2.0.0
  - numpy=1.24.2
  - scipy=1.10.1
  - matplotlib=3.8.2
  - scikit-learn=1.5.0
  - xgboost=2.0.3
  - ete3=3.1.3
  - biopython=1.83
  - r-base=4.3.2
  - r-ggplot2=3.5.0
  - r-dplyr=1.1.4
  - r-tidyr=1.3.1
  - r-tidyverse=2.0.0
  - r-data.table=1.15.2
  - r-viridis=0.6.5
  - r-forcats=1.0.0
  - r-reshape2=1.4.4
  - r-caret=6.0_94
  - r-readxl=1.4.3
  - r-rlang=1.1.3
  - r-gridextra=2.3
  - r-readr=2.1.5
  - pip
  - pip:
      - logging==0.5.1.2
      - argparse==1.1
